<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php
	$clan = "Something Lounge";
	echo '<meta name="keywords" content="KoL, loathing, KoLmafia, kingdom of loathing, clan, leaderboard, snapshot, ' . $clan . '">';
	echo '<meta name="description" content="' . $clan . ' Ascension snapshots.">';
	echo '<meta name="author" content="Richard Harvey Illing">';
	echo '<title> Clan Leaderboard Snapshots for ' . $clan . ' </title>';
?>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>